@echo off
c:
cd c:\git\vxframe
SET ROOT_URL=http://localhost
SET NO_BATCH=no
SET MONGO_URL=mongodb://localhost:27017/vxframe
SET MAIL_URL=
SET MAILGUN_PRIVATE_API_KEY=
SET MAILGUN_PUBLIC_API_KEY=
SET MAILGUN_DOMAIN=
SET TWILIO_ACCOUNT_SID=
SET TWILIO_AUTH_TOKEN=
SET TWILIO_FROM_PHONE=
SET TWILIO_ACCOUNT_SID_TEST=
SET TWILIO_AUTH_TOKEN_TEST=
SET TWILIO_FROM_PHONE_TEST=
SET AMAZON_ACCESS_KEY_ID=
SET AMAZON_SECRET_ACCESS_KEY=
SET AMAZON_REGION=
SET METEOR_PROFILE=1000
meteor %1 --port 80